paths:
  '/projects/{project_id}/roles/{role_id}':
    post:
      tags:
        - Roles
      summary: Update project role
      description: Updates an existing project role.
      operationId: update-project-role
      parameters:
        - name: project_id
          in: path
          description: The ID of the project to update.
          required: true
          schema:
            type: string
        - name: role_id
          in: path
          description: The ID of the role to update.
          required: true
          schema:
            type: string
      requestBody:
        description: Fields to update on the project role.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicUpdateOrganizationRoleBody'
        required: true
      responses:
        '200':
          description: Project role updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
      x-oaiMeta:
        name: Update project role
        group: administration
        returns: 'The updated [role object](https://platform.openai.com/docs/api-reference/roles/object).'
        examples:
          request:
            curl: "curl -X POST https://api.openai.com/v1/projects/proj_abc123/roles/role_01J1F8PROJ \\\n  -H \"Authorization: Bearer $OPENAI_ADMIN_KEY\" \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\n      \"role_name\": \"API Project Key Manager\",\n      \"permissions\": [\n          \"api.organization.projects.api_keys.read\",\n          \"api.organization.projects.api_keys.write\"\n      ],\n      \"description\": \"Allows managing API keys for the project\"\n  }'\n"
          response: "{\n    \"object\": \"role\",\n    \"id\": \"role_01J1F8PROJ\",\n    \"name\": \"API Project Key Manager\",\n    \"description\": \"Allows managing API keys for the project\",\n    \"permissions\": [\n        \"api.organization.projects.api_keys.read\",\n        \"api.organization.projects.api_keys.write\"\n    ],\n    \"resource_type\": \"api.project\",\n    \"predefined_role\": false\n}\n"