components:
  schemas:
    EvalStoredCompletionsDataSourceConfig:
      title: StoredCompletionsDataSourceConfig
      required:
        - type
        - schema
      type: object
      properties:
        type:
          enum:
            - stored_completions
          type: string
          description: The type of data source. Always `stored_completions`.
          default: stored_completions
          x-stainless-const: true
        metadata:
          $ref: '#/components/schemas/Metadata'
        schema:
          type: object
          description: "The json schema for the run data source items.\nLearn how to build JSON schemas [here](https://json-schema.org/).\n"
      description: "Deprecated in favor of LogsDataSourceConfig.\n"
      deprecated: true
      x-oaiMeta:
        name: The stored completions data source object for evals
        group: evals
        example: "{\n  \"type\": \"stored_completions\",\n  \"metadata\": {\n    \"language\": \"english\"\n  },\n  \"schema\": {\n    \"type\": \"object\",\n    \"properties\": {\n      \"item\": {\n        \"type\": \"object\"\n      },\n      \"sample\": {\n        \"type\": \"object\"\n      }\n    },\n    \"required\": [\n      \"item\",\n      \"sample\"\n    }\n}\n"